#+title: Doom Emacs Configuration
#+author: Kaidong Hu
#+email: hukaidonghkd@gmail.com
#+property: header-args:emacs-lisp :tangle config.el :results silent

* Prelude

Early initialization and workarounds for compatibility issues. This includes
pre-declaring projectile variables to prevent lexical binding errors in Emacs
28+ and disabling which-key-mode which is enabled by default in Doom.

#+begin_src emacs-lisp
;; Disable which-key-mode (enabled by Doom core in doom-keybinds.el)
(remove-hook 'doom-first-input-hook #'which-key-mode)
#+end_src

* User Information

Personal information used by GPG, email clients, and file templates.

#+begin_src emacs-lisp
(setq user-full-name "Kaidong Hu"
      user-mail-address "hukaidonghkd@gmail.com")
#+end_src

* UI Configuration

Visual appearance settings including theme, fonts, and editor behavior.
Rainbow delimiters help distinguish nested parentheses in programming modes.

#+begin_src emacs-lisp
(add-hook 'prog-mode-hook #'rainbow-delimiters-mode)

(setq doom-theme 'doom-one)
(setq doom-font (font-spec :family "Berkeley Mono Variable" :size 13 :weight 'semi-bold))
(setq display-line-numbers-type t)
(setq initial-frame-alist '((width . 180) (height . 55)))
(setq doom-leader-key ",")
(setq doom-localleader-key ", ,")
#+end_src

* No Too Evil

C-u is still useful in many conditions, so we use it as prefix and use alt-v as scrolling alternative.

#+begin_src emacs-lisp
(remove-hook 'doom-first-input-hook #'evil-snipe-mode)

(setq! evil-want-C-u-scroll nil
       evil-want-C-u-delete nil)
#+end_src

* Org Mode

Configuration for org-mode, including the base directory for org files,
refile settings for organizing tasks, and a custom capture template for
quickly adding todos to an inbox.

#+begin_src emacs-lisp
(setq org-directory "~/org/")

(after! org
  (require 'org-tempo)
  
  (setq org-agenda-files '("~/org" "~/org/projects")
        org-refile-targets '((nil :maxlevel . 3) (org-agenda-files :maxlevel . 3))
        org-refile-use-outline-path 'file
        org-refile-allow-creating-parent-nodes 'confirm)
  
  (add-hook 'org-mode-hook
            (lambda () (setq buffer-save-without-query t)))
  
  (add-to-list 'org-capture-templates
               '("t" "Todo" entry (file+headline +org-capture-todo-file "Inbox")
                 "* TODO %?\nSCHEDULED: %t\n%i\n%a" :prepend t)))
#+end_src

* Bibliography

Settings for academic reference management, including BibTeX integration,
citation handling, and literature note templates for use with org-roam.

** Bibtex Completion

Configure bibtex-completion for searching and inserting citations. Sets up
paths for the bibliography file, PDF library, and literature notes. Includes
a template for creating org-roam literature notes with proper metadata.

#+begin_src emacs-lisp
(after! bibtex-completion
  (setq bibtex-completion-bibliography '("~/.config/references.bib")
        bibtex-completion-library-path '("~/papers/")
        bibtex-completion-notes-path "~/org/roam/refs/"

        ;; Use org-cite format when inserting citations in org files
        bibtex-completion-format-citation-functions
        '((org-mode . bibtex-completion-format-citation-org-cite)
          (latex-mode . bibtex-completion-format-citation-cite)
          (default . bibtex-completion-format-citation-default))

        ;; Template for literature notes (one file per entry)
        bibtex-completion-notes-template-multiple-files
        (concat "#+title: ${title}\n"
                "#+filetags: :reference:\n\n"
                "* ${title}\n"
                ":PROPERTIES:\n"
                ":ROAM_REFS: [cite:@${=key=}]\n"
                ":AUTHOR: ${author-or-editor}\n"
                ":YEAR: ${year}\n"
                ":END:\n\n"
                "** Summary\n\n"
                "** Notes\n\n")))
#+end_src

** Bibtex Autokey

Configure bibtex autokey format: author + year + first title word.
Example output: smith2023deep, jones2024reinforcement

#+begin_src emacs-lisp
(after! bibtex
  (setq bibtex-autokey-year-length 4                    ; use full year: 2023
        bibtex-autokey-name-year-separator ""           ; no separator between name and year
        bibtex-autokey-year-title-separator ""          ; no separator between year and title
        bibtex-autokey-titleword-separator ""           ; no separator between title words
        bibtex-autokey-titlewords 1                     ; use 1 word from title
        bibtex-autokey-titlewords-stretch 0             ; don't add extra words
        bibtex-autokey-titleword-length nil             ; use full word (nil = no limit)
        bibtex-autokey-titleword-ignore                 ; words to skip
        '("A" "An" "On" "The" "A" "For" "And" "Of" "In" "To"
          "a" "an" "on" "the" "for" "and" "of" "in" "to")))
#+end_src

** Org-cite

Configure org-cite for native citation support in org-mode. Uses biblatex
for LaTeX export and CSL (Citation Style Language) for other formats.

#+begin_src emacs-lisp
(after! oc
  (setq org-cite-global-bibliography '("~/.config/references.bib")
        org-cite-export-processors '((latex biblatex)
                                     (t csl))))
#+end_src

** Biblio (CrossRef)

Set email for CrossRef API requests. CrossRef uses this to provide better
rate limits and to contact you if there are issues with your queries.

#+begin_src emacs-lisp
(after! biblio
  (setq biblio-crossref-user-email-address "hukaidong@gmail.com"))
#+end_src

** Org-roam-bibtex

Integration between org-roam and bibtex for managing literature notes.
Enables automatic creation of org-roam nodes from bibliography entries
with preformatted metadata fields.

#+begin_src emacs-lisp
(use-package! org-roam-bibtex
  :after org-roam
  :hook (org-roam-mode . org-roam-bibtex-mode)
  :config
  (setq orb-preformat-keywords '("citekey" "title" "author-or-editor" "year" "url" "file")
        orb-process-file-keyword t
        orb-attached-file-extensions '("pdf" "epub")))
#+end_src
